backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
site_url: "https://dev.emeraldroomsalon.com/"
logo_url: "https://d33wubrfki0l68.cloudfront.net/e7bff93bed13616df27fa4426b8d288829d423ba/3e51d/static/logo-f3079e02981bbd16bc1afcb4f9c91c7f.png"
collections:
  - label: "Homepage"
    name: "pages"
    files:
      - file: "src/markdown-pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Headline", name: "h1", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/markdown-pages/location.md"
        label: "Location"  
        name: "location"
        widget: "object"
        fields:
          - {label: "Address", name: "body", widget: "markdown"}
          - label: "Hours"
            name: "hours"
            widget: "object"
            fields:
              - {label: "Sunday", name: "sun", widget: "string"}
              - {label: "Mon-Tues", name: "mon_tue", widget: "string"}
              - {label: "Wed-Thurs", name: "wed_thu", widget: "string"}
              - {label: "Friday", name: "fri", widget: "string"}
              - {label: "Saturday", name: "sat", widget: "string"}
          