backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master) !Change to master when merging dev branch to master
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
site_url: "https://dev.emeraldroomsalon.com/" # !Change to https://emeraldroomsalon.com/ when merging dev branch to master
logo_url: "https://d33wubrfki0l68.cloudfront.net/e7bff93bed13616df27fa4426b8d288829d423ba/3e51d/static/logo-f3079e02981bbd16bc1afcb4f9c91c7f.png"
collections:
  - label: "Main Sections"
    name: "pages"
    files:
      - file: "src/markdown-pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Headline", name: "h1", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/markdown-pages/location.md"
        label: "Location"  
        name: "location"
        widget: "object"
        fields:
          - label: "Hours"
            name: "hours"
            widget: "object"
            fields:
              - {label: "Sunday", name: "sun", widget: "string", required: "false"}
              - {label: "Mon-Tues", name: "mon-tue", widget: "string", required: "false"}
              - {label: "Wed-Thurs", name: "wed-thu", widget: "string", required: "false"}
              - {label: "Friday", name: "fri", widget: "string", required: "false"}
              - {label: "Saturday", name: "sat", widget: "string", required: "false"}
          - {label: "Address", name: "body", widget: "markdown"}
  - label: "Services"
    name: "service-cards"
    folder: "src/markdown-pages/services-cards"
    create: true
    fields:
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Class", name: "class", widget: "hidden", default: "service-card"}
      - {label: "Emoji", name: "emoji", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}