backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Homepage"
    name: "pages"
    files:
      - label: "About Section"
        name: "index"
        file: "/src/markdown-pages/about.md"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}
      - label: "Location Section"  
        name: "location"
        widget: "object"
        fields:
          - label: "Address"
            name: "body"
            file: "/src/markdown-pages/location/address.md"
            fields:
              - {label: "Content", name: "body", widget: "markdown"}