backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
site_url: "https://elegant-mahavira-8f2c94.netlify.com/"
logo_url: "https://d33wubrfki0l68.cloudfront.net/e7bff93bed13616df27fa4426b8d288829d423ba/3e51d/static/logo-f3079e02981bbd16bc1afcb4f9c91c7f.png"
collections:
  - label: "Homepage"
    name: "pages"
    files:
      - file: "/src/markdown-pages/about.md"
        label: "About Section"
        name: "about"
        fields:
          - {label: "Headline", name: "h1", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "/src/markdown-pages/loc/address.md"
        label: "Address"  
        name: "Address"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}