backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "/src/pages/index.js"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}