backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/src/images" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About Section"
        name: "about"
        file: "/src/markdown-pages/about.md"
        fields:
          - {label: Content, name: content, widget: string}